name: DEV Build Atlassian AddOn

on:
  workflow_call:
    inputs:
      ADDON_NAME:
        description: The AddOns Name.
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |-
          docker build \
            -t "europe-west1-docker.pkg.dev/${{ inputs.GCP_PROJECT_ID }}/ricebean-net-dev/${{ inputs.ADDON_NAME }}:1.0.${GITHUB_RUN_NUMBER}" \
            --build-arg VERSION=1.0.${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg GITHUB_SHORT_SHA=${GITHUB_SHA:0:8} \
            --build-arg GITHUB_RUN_ID=${GITHUB_RUN_ID} \
            --build-arg GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_ACTOR=${GITHUB_ACTOR} \
            .

  