name: Publish Atlassian AddOn

on:
  workflow_call:
    inputs:
      ADDON_NAME:
        description: The AddOns Name.
        required: true
        type: string
      GCP_PROJECT_ID:
        description: The GCP Project ID.
        required: false
        type: string
        default: 'rb-net'
      GCP_REGION:
        description: The GCP Region.
        required: false
        type: string
        default: 'europe-west1'
    secrets:
      GCP_SA_KEY:
        required: true

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ inputs.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Docker Auth GCloud
        run: gcloud auth configure-docker

      - name: Build Docker Image
        run: |-
          docker build \
            -t "gcr.io/${{ inputs.GCP_PROJECT_ID }}/${{ inputs.ADDON_NAME }}:1.0.${GITHUB_RUN_NUMBER}" \
            --build-arg BASE_URL=https://${{ inputs.ADDON_NAME }}.atlassian-addon.ricebean.net \
            --build-arg VERSION=1.0.${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_SHA=${GITHUB_SHA} \
            --build-arg GITHUB_SHORT_SHA=${GITHUB_SHA:0:8} \
            --build-arg GITHUB_RUN_ID=${GITHUB_RUN_ID} \
            --build-arg GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER} \
            --build-arg GITHUB_ACTOR=${GITHUB_ACTOR} \
            .

      - name: Push Image to Google Container Registry
        run: docker push "gcr.io/${{ inputs.GCP_PROJECT_ID }}/${{ inputs.ADDON_NAME }}:1.0.${GITHUB_RUN_NUMBER}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1  

      - name: Terraform Apply
        run: terraform apply -auto-aprove
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}